message_publisher:
  type: 'queue_publisher_rabbitmq'
  rabbitmqhost: 'localhost'
  queue_name: 'FACE_EMBEDDING'
message_consumer:
  type: 'queue_consumer_rabbitmq'
  rabbitmqhost: 'localhost'
  queue_name: 'FACE_DETECTION'
face_detector:
  type: 'movidius_ssd'
  movidius_id: 0
  longrange: 1